### ISSUE TITLE
Error Building tools

### ISSUE THREAD

**Issue by Logiraptor** [gdslang/gdsl-toolkit#16]
I'm trying to build the tools under /tools. (semantics-opt, etc). I've built and installed gdsl successfully so far. If I cd into tools and run `make`, I get the following:

```
gcc -c -g3 -std=gnu11 -pedantic -Wall -Wfatal-errors -DRELAXEDFATAL -DRELAXEDFATAL -I../include semantics-cli.c -o semantics-cli.o
semantics-cli.c:10:18: fatal error: gdsl.h: No such file or directory
 #include <gdsl.h>
                  ^
compilation terminated.
make: *** [semantics-cli.o] Error 1
```

Checking in the ../include directory, gdsl.h is a broken symlink to `../gdsl_manual.h`. Is there something I'm missing about how to build the tools?

Thanks

**Comment by jucs** [comment]
Hello,

these tools are primarily used internally for debugging purposes. 
Therefore, they are not included in the official distribution and are 
not built by the Automake makefile. If you want to use them (e.g. for 
x86), you need to run the following command in the main GDSL directory:

make -f Makefile_manual x86

Please contact me if you still have problems building the tools. The 
Makefiles have so far only been tested on Ubuntu.

Greetings,
Julian

**Comment by Logiraptor** [comment]
Ok, Thanks for the info.
