### ISSUE TITLE
Errors with Python and Java Bindings

### ISSUE THREAD

**Issue by Logiraptor** [gdslang/gdsl-toolkit#17]
I want to use GDSL to translate x86 machine code to RREIL then do my own separate analysis on the RREIL, what would be the path of lease resistance to getting access to the RREIL? I see Python and Java bindings. The python bindings give a build error:
```
python setup.py build_ext --inplace
running build_ext
building '_pygdsl' extension
swigging pygdsl.i to pygdsl_wrap.c
swig -python -o pygdsl_wrap.c pygdsl.i
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_CONFIG_H=1 -DGDSL_X86=1 -I../ -I./ -I/usr/include/python2.7 -c pygdsl_wrap.c -o build/temp.linux-x86_64-2.7/pygdsl_wrap.o -std=c11
pygdsl_wrap.c: In function ‘init_pygdsl’:
pygdsl_wrap.c:4142:87: error: ‘CON_SEM_PRESERVATION_EVERYWHERE’ undeclared (first use in this function)
   SWIG_Python_SetConstant(d, "GDSL_SEM_PRESERVATION_EVERYWHERE",SWIG_From_long((long)(CON_SEM_PRESERVATION_EVERYWHERE)));
                                                                                       ^
pygdsl_wrap.c:4142:87: note: each undeclared identifier is reported only once for each function it appears in
pygdsl_wrap.c:4143:82: error: ‘CON_SEM_PRESERVATION_BLOCK’ undeclared (first use in this function)
   SWIG_Python_SetConstant(d, "GDSL_SEM_PRESERVATION_BLOCK",SWIG_From_long((long)(CON_SEM_PRESERVATION_BLOCK)));
                                                                                  ^
pygdsl_wrap.c:4144:84: error: ‘CON_SEM_PRESERVATION_CONTEXT’ undeclared (first use in this function)
   SWIG_Python_SetConstant(d, "GDSL_SEM_PRESERVATION_CONTEXT",SWIG_From_long((long)(CON_SEM_PRESERVATION_CONTEXT)));
                                                                                    ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [_pygdsl.so] Error 1
```

The java bindings have built and appear to work, but the example program fails because `Gdsl.getFrontends()` returns an empty array. I think it's looking in a directory but I haven't found any documentation on where and what I should be configuring so it can find a frontend.

Thanks

**Comment by jucs** [comment]
Hello,

the Python binding has been developed by an external contributor who did not yet update it to match recent changes. Unfortunately, I am not sure about the amount of work that would be necessary to fix it.

Both the bindings to C++ and Java are up-to-date and working. Both bindings are used by projects on our chair. However, there might be some functionality that is missing in either of them - let me know if you need something specific.

For the Java binding, there are multiple ways to choose from for the search for frontends. Generally, a frontend is called 'libgdsl-[configuration].so', e.g. 'libgdsl-x86-rreil.so' for the x86-rreil frontend. If you simply invoke Gdsl.getFrontends() as done by the toy example in libs/jgdsl/Program.java, the frontend search path is expected in the environment variable GDSL_FRONTENDS. There are options to search the frontend in the system library path, let me know if you want to use this.

Greetings,
Julian

**Comment by Logiraptor** [comment]
Ok, I've set GDSL_FRONTENDS to the .libs directory that was created during the build process. I think it is finding the frontends now, but it's crashing in the native code:
```
*** Error in `java': realloc(): invalid old size: 0x00007f63e69da830 ***
```

I ran it through gdb and traced it to [this](https://github.com/gdslang/gdsl-toolkit/blob/master/libs/gdsl-multiplex/src/gdsl_multiplex.c#L74) `realloc` call in gdsl_multiplex.c

**Comment by Logiraptor** [comment]
Hello again. Upon further inspection, we noticed that the realloc call should be 
```
*descs = (struct frontend_desc*) realloc(*descs, sizeof(struct frontend_desc) * frontends_size);
```
There was a missing '*' just before descs in the argument list.

The program makes it a bit farther now, but ends with: 
```
Exception in thread "main" java.lang.RuntimeException: Unable to open frontend: Symbol not found
	at gdsl.ListFrontend.getFrontendPtrByDesc(Native Method)
	at gdsl.ListFrontend.initializeNative(ListFrontend.java:52)
	at gdsl.ListFrontend.<init>(ListFrontend.java:32)
	at gdsl.Gdsl.getFrontendsNative(Native Method)
	at gdsl.Gdsl.getFrontends(Gdsl.java:97)
	at Program.sub(Program.java:27)
	at Program.main(Program.java:74)
```

This makes me think that maybe I haven't configured it right and it's finding the wrong `libgdsl-x86-rreil.so`. If you have any tips on where I should be looking, I'd appreciate it.

Thanks

**Comment by bmihaila** [comment]
Hi

I have been using the Java bindings in the [Bindead](https://bitbucket.org/mihaila/bindead) project for a while now and we managed to iron out some bugs during that process with Julian. The error above rings a bell and I think you are right about not finding the right lib in the path. However, I do not seem to encounter the `realloc()` error (more on that at the end of the post).

I just tried out the latest commit d628468703ddfc9dc12027b0194a6cb2c84bd9cb and it seems to work in my setting (see the initialization process in these files [x32-Java-Dis](https://bitbucket.org/mihaila/bindead/src/4885006b108fd6b84fbbe3e889670660f85df0aa/binspot/detail/main/java/binspot/gdsl/GdslX86_32Disassembler.java?at=master) and [GDSL-Native-Dis](https://bitbucket.org/mihaila/bindead/src/4885006b108fd6b84fbbe3e889670660f85df0aa/binspot/detail/main/java/binspot/gdsl/GdslNativeDisassembler.java?at=master) ). Here some more details:
I set the environment `LD_LIBRARY_PATH` to contain the GDSL libs installation path. Debugging the loading code it seems that the method `"private native long getFrontendPtrByLibName (String name)"` in `BareFrontend.java` is called with the string `"x86-rreil"` which is enough to load the library in Java. As mentioned this setting was the first usage of the Java bindings and the method still works for me.

On the other side I did not set the `GDSL_FRONTENDS` environment variable. So apparently if I invoke `Gdsl.getFrontends()` it returns an empty array. Now that I tried setting the variable to the path of the GDSL libs I run into the same `realloc()` error you describe above. Seems like there is a bug there. Julian should look into this and till then you can try using the method of directly specifying the frontend (i.e. the GDSL lib) as I described above.

Bye
Bogdan

**Comment by jucs** [comment]
Hello,

thank you Bogdan for your help here :-). The reason that the memory bug has not yet been encountered is that it only occurs if the initial array for the frontends of size 8 is too small. However, now that we support more architectures, there are more 8 libraries called libgdsl-*.so in the .libs folder after a standard build. Thank you for the report, the bug should be fixed now.

The new problem that you are stuck with now is caused by the other frontends in that folder that are also called libgdsl-*.so, but are no valid frontends for the Java binding. This applies to frontends that do not include semantics. The easiest way to fix this is to only build a specific frontend that includes semantics. If you want to use the x86-rreil frontend, run the following commands:

make clean && ../configure --with-frontend=x86-rreil && make

Of course you could also copy the valid frontends somewhere else (and use that path for GDSL_FRONTENDS) or explicitly load the frontend you want as Bogdan pointed out. If you want to do that, I can provide more details.

**Comment by Logiraptor** [comment]
Excellent. Building a single frontend did it. I can now disassemble x86 and translate it to RREIL. Thank you both for your help.

**Comment by jucs** [comment]
Great :-)
