### ISSUE TITLE
Library cppgdsl lin_scale has no to_string implementation

### ISSUE THREAD

**Issue by jeffball55** [gdslang/gdsl-toolkit#21]
The include file for lin_scale in the cppgdsl library references a `to_string` method.  However the lin_scale cpp file (libs/cppgdsl/src/rreil/linear/lin_scale.cpp) does not have an implementation for this method.  However, the class that lin_scale inherits from (linear) implements this method.

The problem comes from the compiler trying to fetch the lin_scale's implementation, which does not exist.  Thus the following error is generated:
```
classifier.o: In function `the_visitor::visit(gdsl::rreil::lin_scale*)':
./example.cpp:68: undefined reference to `gdsl::rreil::lin_scale::to_string()'
```
I was able to work around the issue by removing the following line from lin_scale.h:
```
36   std::string to_string();
```

**Comment by jucs** [comment]
Thank you for your detailed bug report and sorry for my slow response. Your proposed fix has been committed :-).
